name: Create release

on:
  push:
    tags: [ v* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ${{ github.event.head_commit.message }}
            https://github.com/tankibaj/discord-themoviedb-bot/tag/${{ github.ref }}
          draft: false
          prerelease: false
